### PR TITLE
Support for checkServerIdentity https option

### PR DESCRIPTION
**Pull request by jkryl**

### CODE REVIEW

**Comment by DonutEspresso** [comment]
Thanks for the PR! Would you mind adding some tests to verify that this is working?

**Comment by jkryl** [comment]
sure, I will try to find some time next week and add those tests. thanks

**Comment by jkryl** [comment]
@DonutEspresso: done. I think PR is ready to be merged.

**Comment by simonepri** [comment]
@DonutEspresso what about the status of this PR? Can be marged?

**Comment by DonutEspresso** [comment]
Apologies for delay on this! I think this looks fine. 

@retrohacker @yunong any concerns?

**Comment by DonutEspresso** [comment]
This has been rebased against master and merged in #155. Apologies for the delay. 😞  We'll get a new version out ASAP!

**Pull request closed without merging**
