### PR TITLE
node-restify #895: Defacto Standard: field[]=a&field[]=b&field[]=c becomes field=["a","b","c"] 

### PR DESCRIPTION
**Pull request by jmealo**
# The changes in this PR must be merged prior to: https://github.com/restify/node-restify/issues/896

**This PR is a companion PR to https://github.com/restify/node-restify/issues/896 which changes the server components**

This PR addresses [#444](https://github.com/restify/node-restify/issues/444) and [#896](https://github.com/restify/node-restify/issues/895) by implementing array handling in both query string and body parsing/serialization for both the client and server components. It includes tests where relevant.

This is the behavior in PHP, Ruby and ASP.NET and jQuery's `.param` making this a defacto standard.
## Behavior

Input:

``` php
field[]=a
field[]=b
field[]=c
```

Output:

``` javascript
field = ["a","b","c"]
```

Input:

``` php
pizza[left]=pepperoni
pizza[right]=anchovies
```

Output:

``` javascript
pizza = { "left": "pepperoni", "right": "anchovies" }
```

Input:

``` php
pizza[left][]=pepperoni
pizza[left][]=bacon
pizza[right][]=anchovies
```

Output:

``` javascript
pizza = { "left": ["pepperoni", "bacon"], "right": ["anchovies"] }
```

This PR makes use of the MIT licensed [edwardsmit/node-qs-serialization](https://github.com/edwardsmit/node-qs-serialization) which is based upon battle tested jQuery code.

### CODE REVIEW

**Comment by yunong** [comment]
@trentm I know you've been working on query strings lately, mind taking a look at this?

**Comment by trentm** [comment]
@yunong Yup, sure. Actually I kinda of did here: https://github.com/restify/node-restify/issues/895#issuecomment-256194264

Basically I don't see a *need* for the restify *clients* to switch to using the "qs" module to get this bracket notation for an array of items, because the current serialization (e.g. `?field=a&field=b`) is already interpreted correctly by the latest restify@4.x.

@jmealo and others: Thoughts?

**Comment by jmealo** [comment]
@trentm: This allows the restify client to communicate with backends implemented in PHP, ASP.NET and Ruby (and apparently restify itself).

**Comment by retrohacker** [comment]
Hey all. I would still like to see this land if there is still a need for it in the community. That being said, there isn't a current champion for this work to carry it over the finish line. While the work here is amazing, and comes complete with tests (!!!), the code base has moved out from under this PR (and the corresponding PR on the client repo). I'd like to move this to the https://github.com/restify/node-restify/blob/5.x/FEATURE_REQUESTS.md document in this repo until someone comes along looking for this feature.

My motivation here is that this PR has been a failure on the part of us, the maintainers, and this very well may still be something that the community would like to see happen. There are potential champions out there that may come to this repo looking to create a new PR for this feature only to find this existing PR that has stagnated. If I were to come here with a fresh set of eyes ready to contribute work and I found this, I would lose my motivation and assume this feature will never land.

In that spirit, I'd like to close this and give the community the chance to resurface this as a feature request. If anyone strongly disagrees, we can reopen and discuss.

**Pull request closed without merging**
